spring.application.name=project-publisher
server.port=8081
jenkins.auth.token=117abc52f5ee2d56672b61904b0945b393
jenkins.auth.username=admin
jenkins.server.url=http://localhost:8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

template.job = 'testProject_001'