/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/put/item/Button.vue')['default']
    DatePicker: typeof import('./src/components/put/item/DatePicker.vue')['default']
    Ellipsis: typeof import('./src/components/put/item/Ellipsis.vue')['default']
    Equation: typeof import('./src/components/put/item/Equation.vue')['default']
    Form: typeof import('./src/components/put/item/Form.vue')['default']
    FormItem: typeof import('./src/components/put/item/FormItem.vue')['default']
    Grid: typeof import('./src/components/put/item/Grid.vue')['default']
    Image: typeof import('./src/components/put/item/Image.vue')['default']
    JsonRenderer: typeof import('./src/components/put/JsonRenderer.vue')['default']
    JsonRendererContainer: typeof import('./src/components/put/JsonRendererContainer.vue')['default']
    JsonRendererItem: typeof import('./src/components/put/JsonRendererItem.vue')['default']
    JsonRendererItemContainer: typeof import('./src/components/put/JsonRendererItemContainer.vue')['default']
    JsonRendererList: typeof import('./src/components/put/JsonRendererList.vue')['default']
    List: typeof import('./src/components/put/item/List.vue')['default']
    ListItem: typeof import('./src/components/put/item/ListItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    Page: typeof import('./src/components/put/item/Page.vue')['default']
    Radio: typeof import('./src/components/put/item/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/put/item/RadioGroup.vue')['default']
    RichText: typeof import('./src/components/put/item/RichText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/put/item/TextInput.vue')['default']
  }
}
